-- Under the SQLPOOL1 Database there is the [dbo].[NYCTaxiTripSmall] we have created in the load data dedicated script. Left click on it and then 'select first 100 rows'

SELECT TOP (100) [DateID]
,[MedallionID]
,[HackneyLicenseID]
,[PickupTimeID]
,[DropoffTimeID]
,[PickupGeographyID]
,[DropoffGeographyID]
,[PickupLatitude]
,[PickupLongitude]
,[PickupLatLong]
,[DropoffLatitude]
,[DropoffLongitude]
,[DropoffLatLong]
,[PassengerCount]
,[TripDurationSeconds]
,[TripDistanceMiles]
,[PaymentType]
,[FareAmount]
,[SurchargeAmount]
,[TaxAmount]
,[TipAmount]
,[TollsAmount]
,[TotalAmount]
 FROM [dbo].[NYCTaxiTripSmall]
